Repository shopinvader/odoo-shopinvader-payment, pull requests merged in 2020-05, with the labels that each got.

#31 [12.0] modernize CI
  .pre-commit-config.yaml
  .pylintrc
  .travis.yml
  test-requirements.txt
Labels: 12.0, bot is merging ⏳

#32 [13.0] modernize CI
  .pre-commit-config.yaml
  .pylintrc
  .travis.yml
  test-requirements.txt
Labels: 13.0, bot is merging ⏳

#30 [10.0] modernize CI
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  invader_sale_payment/__manifest__.py
  test-requirements.txt
Labels: 10.0, bot is merging ⏳

#35 [12.0][IMP] pin flake8
  .pre-commit-config.yaml
  test-requirements.txt
Labels: bot is merging ⏳

#36 [13.0][IMP] pin flake8
  .pre-commit-config.yaml
  test-requirements.txt
Labels: bot is merging ⏳
