Repository shopinvader/odoo-shopinvader-payment, pull requests merged in 2021-07, with the labels that each got.

#40 14.0 migration
  .pre-commit-config.yaml
  invader_payment/__manifest__.py
  invader_payment/services/invader_payment_service.py
  invader_payment_manual/__manifest__.py
  invader_payment_manual/data/payment_acquirer_data.xml
  invader_payment_manual/services/payment_manual.py
  requirements.txt
  setup/invader_payment/odoo/addons/invader_payment
  setup/invader_payment/setup.py
  setup/invader_payment_manual/odoo/addons/invader_payment_manual
  setup/invader_payment_manual/setup.py
  setup/shopinvader_payment/odoo/addons/shopinvader_payment
  setup/shopinvader_payment/setup.py
  setup/shopinvader_payment_manual/odoo/addons/shopinvader_payment_manual
  setup/shopinvader_payment_manual/setup.py
  shopinvader_locomotive_payment_adyen/__manifest__.py
  shopinvader_payment/__manifest__.py
  shopinvader_payment/components/payment_transaction_event_listerner.py
  shopinvader_payment/security/security.xml
  shopinvader_payment/tests/test_payment.py
  shopinvader_payment/views/backend_view.xml
  shopinvader_payment/views/shopinvader_menu.xml
  shopinvader_payment/views/shopinvader_payment_view.xml
  shopinvader_payment_adyen/__manifest__.py
  shopinvader_payment_manual/__manifest__.py
  shopinvader_payment_manual/demo/payment_demo.xml
  shopinvader_payment_manual/tests/test_payment_manual.py
  shopinvader_payment_paypal/__manifest__.py
  shopinvader_quotation_payment/__manifest__.py
  test_invader_payment/__manifest__.py
  test_shopinvader_payment/__manifest__.py
Labels: approved, bot is merging ⏳, migration, needs review

#28 [IMP] 12.0 add differed capture for stripe payments
  invader_payment_stripe/__init__.py
  invader_payment_stripe/models/__init__.py
  invader_payment_stripe/models/payment.py
  invader_payment_stripe/services/payment_stripe.py
  shopinvader_payment/components/payment_transaction_event_listerner.py
  shopinvader_payment/services/invader_payment_service.py
  test_shopinvader_payment/tests/test_shopinvader_payment_stripe.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#45 [FIX] do not set last_sale when not in customer session
  shopinvader_payment/components/payment_transaction_event_listerner.py
Labels: 13.0, approved, bot is merging ⏳, ready to merge

#54 14.0 port pr 53 45
  shopinvader_payment/components/payment_transaction_event_listerner.py
Labels: approved, bot is merging ⏳
