Repository shopinvader/odoo-shopinvader-payment, pull requests merged in 2021-03, with the labels that each got.

#38 [13.0][MIG] invader_payment_sips, shopinvader_payment_sips
  .pre-commit-config.yaml
  invader_payment_sips/__manifest__.py
  invader_payment_sips/demo/payment_demo.xml
  invader_payment_sips/services/payment_sips.py
  setup/invader_payment_sips/odoo/addons/invader_payment_sips
  setup/invader_payment_sips/setup.py
  setup/shopinvader_payment_sips/odoo/addons/shopinvader_payment_sips
  setup/shopinvader_payment_sips/setup.py
  shopinvader_payment_sips/__manifest__.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#48 [13.0] Update dotfiles
  .copier-answers.yml
  .github/workflows/test.yml
  .isort.cfg
  .pre-commit-config.yaml
Labels: 13.0, bot is merging ⏳

#49 [13.0] Test with OCB
  .copier-answers.yml
  .github/workflows/test.yml
Labels: 13.0, bot is merging ⏳

#50 [10.0] Update dotfiles (github actions)
  .copier-answers.yml
  .editorconfig
  .eslintrc.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  invader_payment/models/invader_payable.py
  invader_payment/services/invader_payment_service.py
  invader_payment_sips/services/payment_sips.py
  invader_payment_stripe/services/payment_stripe.py
  requirements.txt
  shopinvader_payment/components/payment_transaction_event_listerner.py
  shopinvader_quotation_payment/services/invader_payment_service.py
  test_invader_payment/tests/test_invader_payment_sips.py
  test_invader_payment/tests/test_invader_payment_stripe.py
  test_shopinvader_payment/tests/test_shopinvader_payment_manual.py
  test_shopinvader_payment/tests/test_shopinvader_quotation_payment.py
Labels: 10.0
