Repository shopinvader/odoo-shopinvader-payment, pull requests merged in 2021-12, with the labels that each got.

#64 [14.0][IMP] shopinvader_payment: Add common fake test payment services
  shopinvader_payment/tests/common.py
  shopinvader_payment/tests/fake_payment.py
Labels: enhancement, needs review, bot is merging ⏳

#55 [MIG] 14.0 Stripe
  .pre-commit-config.yaml
  invader_payment_stripe/__manifest__.py
  invader_payment_stripe/demo/payment_demo.xml
  invader_payment_stripe/services/payment_stripe.py
  requirements.txt
  setup/invader_payment_stripe/odoo/addons/invader_payment_stripe
  setup/invader_payment_stripe/setup.py
  setup/shopinvader_payment_stripe/odoo/addons/shopinvader_payment_stripe
  setup/shopinvader_payment_stripe/setup.py
  shopinvader_payment_stripe/__manifest__.py
  shopinvader_payment_stripe/demo/payment_demo.xml
  shopinvader_payment_stripe/readme/CONTRIBUTORS.rst
  shopinvader_payment_stripe/tests/__init__.py
  shopinvader_payment_stripe/tests/test_payment_stripe.py
Labels: approved, ready to merge, bot is merging ⏳

#65 [IMP] move related test from test_shopinvader_payment into shopinvade…
  shopinvader_payment_manual/tests/test_payment_manual.py
  test_shopinvader_payment/tests/__init__.py
  test_shopinvader_payment/tests/test_shopinvader_payment_manual.py
Labels: bot is merging ⏳
