Repository shopinvader/odoo-shopinvader-payment, pull requests merged in 2022-06, with the labels that each got.

#73 [14.0][UPD] pre-commit
  .pre-commit-config.yaml
  invader_payment_manual/services/payment_manual.py
  shopinvader_payment/tests/fake_payment.py
Labels: bot is merging ⏳

#66 [14.0][ADD] shopinvader_payment_condition
  setup/shopinvader_payment_condition/odoo/addons/shopinvader_payment_condition
  setup/shopinvader_payment_condition/setup.py
  shopinvader_payment_condition/__init__.py
  shopinvader_payment_condition/__manifest__.py
  shopinvader_payment_condition/models/__init__.py
  shopinvader_payment_condition/models/shopinvader_payment.py
  shopinvader_payment_condition/readme/CONFIGURE.rst
  shopinvader_payment_condition/readme/CONTRIBUTORS.rst
  shopinvader_payment_condition/readme/DESCRIPTION.rst
  shopinvader_payment_condition/services/__init__.py
  shopinvader_payment_condition/services/abstract_payable_sale.py
  shopinvader_payment_condition/tests/__init__.py
  shopinvader_payment_condition/tests/test_payment.py
  shopinvader_payment_condition/views/shopinvader_payment.xml
Labels: approved, ready to merge, bot is merging ⏳

#72 [IMP] shop/invader_payment: Add payment transactions to payable returned dict
  invader_payment/models/invader_payable.py
  invader_payment/services/invader_payment_service.py
  shopinvader_payment/models/sale_order.py
  shopinvader_payment/services/__init__.py
  shopinvader_payment/services/abstract_sale.py
  shopinvader_payment/services/cart.py
  shopinvader_payment/tests/test_payment.py
Labels: enhancement, approved, ready to merge, needs review, bot is merging ⏳
